---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lapakan3/video.lapakanik.co.id
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R route $DEPLOYPATH

    # - /bin/cp index.html $DEPLOYPATH
